provider:
  name: faas
  gateway: http://localhost:8080

functions:
  gh-push:
    lang: go
    handler: ./gh-push
    image: alexellis2/gh-push:0.2.1
    environment:
      # Http_X_Github_Event: push
      read_timeout: 5
      write_timeout: 5
      write_debug: true
      read_debug: true
      validate_customers: true
      customers_url: "https://raw.githubusercontent.com/openfaas/openfaas-cloud/master/CUSTOMERS"
      
    environment_file:
      - gateway_config.yml
      - github.yml

  git-tar:
    lang: dockerfile
    handler: ./git-tar
    image: alexellis2/of-git-tar:0.2.2
    environment:
      read_timeout: 120
      write_timeout: 120
      write_debug: true
      read_debug: true
    environment_file:
      - gateway_config.yml

  buildshiprun:
    lang: go
    handler: ./buildshiprun
    image: alexellis2/of-buildshiprun:0.0.2
    environment:
      read_timeout: 300
      write_timeout: 300
      write_debug: true
      read_debug: true
      builder_url: http://of-builder:8080/
    environment_file:
      - buildshiprun_limits_swarm.yml
      - gateway_config.yml

  list-functions:
    lang: go
    handler: ./list-functions
    image: alexellis2/list-functions:0.2
    environment:
      write_debug: true
      read_debug: true
    environment_file:
      - gateway_config.yml

  garbage-collect:
    lang: go
    handler: ./garbage-collect
    image: alexellis2/garbage-collect:0.2
    environment:
      write_debug: true
      read_debug: true
      read_timeout: 30
      write_timeout: 30
    environment_file:
      - gateway_config.yml
      
  git-event:
    lang: go
    handler: ./git-event
    image: alexellis2/git-event:0.2
    environment:
      write_debug: true
      read_debug: true
    environment_file:
      - github.yml
      - gateway_config.yml

  audit-event:
    skip_build: true
    image: functions/alpine:latest
    fprocess: cat
    environment:
      write_debug: true
      read_debug: true
