provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  system-github-event:
    lang: go
    handler: ./github-event
    image: functions/github-event:0.9.2
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      validate_hmac: true
      write_debug: true
      read_debug: true
      validate_customers: true
    environment_file:
      - github.yml
      - gateway_config.yml
    secrets:
      - github-webhook-secret
      - payload-secret
      - customers
    limits:
      memory: 128Mi
    requests:
      memory: 32Mi
      cpu: 50m

  github-push:
    lang: go
    handler: ./github-push
    image: functions/github-push:0.7.5
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      validate_hmac: true
      read_timeout: 10s
      write_timeout: 10s
      write_debug: true
      read_debug: true
    environment_file:
      - gateway_config.yml
      - github.yml
    secrets:
      - github-webhook-secret
      - payload-secret
      - customers
    limits:
      memory: 128Mi
    requests:
      memory: 32Mi
      cpu: 50m
# TODO waterdrips, this dockerfile multiarch?
  git-tar:
    lang: dockerfile
    handler: ./git-tar
    image: functions/of-git-tar:0.19.0
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      read_timeout: 15m
      write_timeout: 15m
      write_debug: true
      read_debug: true
    environment_file:
      - gateway_config.yml
      - github.yml
    secrets:
      - payload-secret
      - private-key
  # Uncomment this for GitLab
  #      - gitlab-api-token
    limits:
      memory: 128Mi
    requests:
      memory: 32Mi
      cpu: 50m

  buildshiprun:
    lang: go
    handler: ./buildshiprun
    image: functions/of-buildshiprun:0.14.0
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      read_timeout: 5m
      write_timeout: 5m
      write_debug: true
      read_debug: true
      scaling_factor: 50
    environment_file:
      - buildshiprun_limits.yml
      - gateway_config.yml
      - github.yml
    secrets:
      - basic-auth-user
      - basic-auth-password
      - payload-secret
  #      - swarm-pull-secret
    limits:
      memory: 128Mi
    requests:
      memory: 32Mi
      cpu: 50m

  garbage-collect:
    lang: go
    handler: ./garbage-collect
    image: functions/garbage-collect:0.4.7
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      write_debug: true
      read_debug: true
      read_timeout: 30s
      write_timeout: 30s
    environment_file:
      - gateway_config.yml
    secrets:
      - basic-auth-user
      - basic-auth-password
      - payload-secret
    limits:
      memory: 128Mi
    requests:
      memory: 32Mi
      cpu: 50m

  github-status:
    lang: go
    handler: ./github-status
    image: functions/github-status:0.5.0
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      write_debug: true
      read_debug: true
      combine_output: false
      validate_hmac: true
      debug_token: true
    environment_file:
      - gateway_config.yml
      - github.yml
    secrets:
      - private-key
      - payload-secret
    limits:
      memory: 128Mi
    requests:
      memory: 32Mi
      cpu: 50m

  import-secrets:
    lang: go
    handler: ./import-secrets
    image: functions/import-secrets:0.6.2
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      write_debug: false
      read_debug: false
      validate_hmac: true
      combined_output: false
    environment_file:
      - github.yml
    secrets:
      - payload-secret
    limits:
      memory: 128Mi
    requests:
      memory: 32Mi
      cpu: 50m

  pipeline-log:
    lang: go
    handler: ./pipeline-log
    image: functions/pipeline-log:0.3.5
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      write_debug: false
      read_debug: false
      combine_output: false
    environment_file:
      - gateway_config.yml
    secrets:
      - s3-access-key
      - s3-secret-key
      - payload-secret
    limits:
      memory: 128Mi
    requests:
      memory: 32Mi
      cpu: 50m

  list-functions:
    lang: go
    handler: ./list-functions
    image: functions/list-functions:0.6.0
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      write_debug: false
      read_debug: false
    environment_file:
      - gateway_config.yml
    secrets:
      - basic-auth-user
      - basic-auth-password
    limits:
      memory: 128Mi
    requests:
      memory: 32Mi
      cpu: 50m

  audit-event:
    lang: go
    handler: ./audit-event
    image: functions/audit-event:0.1.2
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment_file:
      - slack.yml
    limits:
      memory: 128Mi
    requests:
      memory: 32Mi
      cpu: 50m

  echo:
    skip_build: true
    image: functions/alpine:latest
    fprocess: cat
    labels:
      openfaas-cloud: "1"
      com.openfaas.scale.zero: false
    environment:
      write_debug: true
      read_debug: true
    limits:
      memory: 128Mi
    requests:
      memory: 32Mi
      cpu: 50m

  metrics:
    lang: go
    handler: ./metrics
    image: functions/system-metrics:0.2.0
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment_file:
      - gateway_config.yml
    environment:
      content_type: "application/json"
    limits:
      memory: 128Mi
    requests:
      memory: 32Mi
      cpu: 50m

  function-logs:
    lang: go
    handler: ./function-logs
    image: functions/function-logs:0.2.0
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      write_debug: true
      read_debug: true
    environment_file:
      - gateway_config.yml
    secrets:
      - basic-auth-user
      - basic-auth-password
    limits:
      memory: 128Mi
    requests:
      memory: 32Mi
      cpu: 50m
