provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  github-push:
    lang: go
    handler: ./github-push
    image: alexellis2/github-push:0.5.4
    labels:
      openfaas-cloud: "1"
    environment:
      # Http_X_Github_Event: push
      validate_hmac: true
      read_timeout: 10s
      write_timeout: 10s
      write_debug: true
      read_debug: true
      validate_customers: true
    environment_file:
      - gateway_config.yml
      - github.yml
    secrets:
      - github-webhook-secret

  git-tar:
    lang: dockerfile
    handler: ./git-tar
    image: alexellis2/of-git-tar:0.7.3
    labels:
      openfaas-cloud: "1"
    environment:
      read_timeout: 15m
      write_timeout: 15m
      write_debug: true
      read_debug: true
    environment_file:
      - gateway_config.yml
      - github.yml
    secrets:
      - github-webhook-secret

  buildshiprun:
    lang: go
    handler: ./buildshiprun
    image: alexellis2/of-buildshiprun:0.5.3
    labels:
      openfaas-cloud: "1"
    environment:
      read_timeout: 5m
      write_timeout: 5m
      write_debug: true
      read_debug: true
    environment_file:
      - buildshiprun_limits_swarm.yml
      - gateway_config.yml
      - github.yml
    secrets:
      - basic-auth-user
      - basic-auth-password
      - github-webhook-secret
#      - registry-auth

  list-functions:
    lang: go
    handler: ./list-functions
    image: alexellis2/list-functions:0.4.3
    labels:
      openfaas-cloud: "1"
    environment:
      write_debug: true
      read_debug: true
    environment_file:
      - gateway_config.yml
    secrets:
      - basic-auth-user
      - basic-auth-password

  garbage-collect:
    lang: go
    handler: ./garbage-collect
    image: alexellis2/garbage-collect:0.3.4
    labels:
      openfaas-cloud: "1"
    environment:
      write_debug: true
      read_debug: true
      read_timeout: 30s
      write_timeout: 30s
    environment_file:
      - gateway_config.yml
    secrets:
      - basic-auth-user
      - basic-auth-password

  github-status:
    lang: go
    handler: ./github-status
    image: alexellis2/github-status:0.1.3
    environment:
      write_debug: true
      read_debug: true
      combine_output: false
      validate_hmac: true
    environment_file:
      - gateway_config.yml
      - github.yml
    secrets:
      - private-key
      - github-webhook-secret

  github-event:
    lang: go
    handler: ./github-event
    image: alexellis2/github-event:0.4.4
    labels:
      openfaas-cloud: "1"
    environment:
      write_debug: true
      read_debug: true
    environment_file:
      - github.yml
      - gateway_config.yml
    secrets:
      - github-webhook-secret

  import-secrets:
    lang: go
    handler: ./import-secrets
    image: alexellis2/import-secrets:0.2.2
    labels:
      openfaas-cloud: "1"
    environment:
      write_debug: true
      read_debug: true
      validate_hmac: true
      combined_output: false
    environment_file:
      - github.yml
    secrets:
      - github-webhook-secret

  echo:
    skip_build: true
    image: functions/alpine:latest
    fprocess: cat
    environment:
      write_debug: true
      read_debug: true

  audit-event:
    lang: go
    handler: ./audit-event
    image: functions/audit-event:0.1.0
    labels:
      openfaas-cloud: "1"
    environment_file:
      - slack.yml

  pipeline-log:
    lang: go
    handler: ./pipeline-log
    image: alexellis2/pipeline-log:latest
    environment:
      write_debug: true
      read_debug: true
      combine_output: false
    environment_file:
      - gateway_config.yml
    secrets:
      - s3-access-key
      - s3-secret-key
