provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  system-github-event:
    lang: go
    handler: ./github-event
    image: functions/github-event:0.8.1
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      validate_hmac: true
      write_debug: true
      read_debug: true
      validate_customers: true
    environment_file:
      - github.yml
      - gateway_config.yml
    secrets:
      - github-webhook-secret
      - payload-secret

  github-push:
    lang: go
    handler: ./github-push
    image: functions/github-push:0.7.3
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      validate_hmac: true
      read_timeout: 10s
      write_timeout: 10s
      write_debug: true
      read_debug: true
    environment_file:
      - gateway_config.yml
      - github.yml
    secrets:
      - github-webhook-secret
      - payload-secret

  git-tar:
    lang: dockerfile
    handler: ./git-tar
    image: functions/of-git-tar:0.13.0
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      read_timeout: 15m
      write_timeout: 15m
      write_debug: true
      read_debug: true
    environment_file:
      - gateway_config.yml
      - github.yml
    secrets:
      - payload-secret
      - private-key
  # Uncomment this for GitLab
  #      - gitlab-api-token

  buildshiprun:
    lang: go
    handler: ./buildshiprun
    image: functions/of-buildshiprun:0.11.2
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      read_timeout: 5m
      write_timeout: 5m
      write_debug: true
      read_debug: true
      scaling_factor: 50
    environment_file:
      - buildshiprun_limits.yml
      - gateway_config.yml
      - github.yml
    secrets:
      - basic-auth-user
      - basic-auth-password
      - payload-secret
  #      - swarm-pull-secret

  garbage-collect:
    lang: go
    handler: ./garbage-collect
    image: functions/garbage-collect:0.4.4
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      write_debug: true
      read_debug: true
      read_timeout: 30s
      write_timeout: 30s
    environment_file:
      - gateway_config.yml
    secrets:
      - basic-auth-user
      - basic-auth-password
      - payload-secret

  github-status:
    lang: go
    handler: ./github-status
    image: functions/github-status:0.3.6
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      write_debug: true
      read_debug: true
      combine_output: false
      validate_hmac: true
      debug_token: true
    environment_file:
      - gateway_config.yml
      - github.yml
    secrets:
      - private-key
      - payload-secret

  import-secrets:
    lang: go
    handler: ./import-secrets
    image: functions/import-secrets:0.3.3
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      write_debug: true
      read_debug: true
      validate_hmac: true
      combined_output: false
    environment_file:
      - github.yml
    secrets:
      - payload-secret

  pipeline-log:
    lang: go
    handler: ./pipeline-log
    image: functions/pipeline-log:0.3.3
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      write_debug: true
      read_debug: true
      combine_output: false
    environment_file:
      - gateway_config.yml
    secrets:
      - s3-access-key
      - s3-secret-key
      - payload-secret

  list-functions:
    lang: go
    handler: ./list-functions
    image: functions/list-functions:0.4.8
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      write_debug: true
      read_debug: true
    environment_file:
      - gateway_config.yml
    secrets:
      - basic-auth-user
      - basic-auth-password

  audit-event:
    lang: go
    handler: ./audit-event
    image: functions/audit-event:0.1.2
    labels:
      openfaas-cloud: "1"
      com.openfaas.scale.zero: false
    environment_file:
      - slack.yml

  echo:
    skip_build: true
    image: functions/alpine:latest
    fprocess: cat
    labels:
      openfaas-cloud: "1"
      com.openfaas.scale.zero: false
    environment:
      write_debug: true
      read_debug: true

  system-metrics:
    lang: go
    handler: ./system-metrics
    image: functions/system-metrics:0.1.1
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment_file:
      - gateway_config.yml
    environment:
      content_type: "application/json"

