apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: of-builder
  namespace: openfaas
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io.scrape: "false"
      labels:
        app: of-builder
    spec:
      volumes:
        - name: registry-secret
          secret:
            secretName: registry-secret
      containers:
      - name: of-builder
        image: openfaas/of-builder:0.5.3
        imagePullPolicy: Always
        env:
          - name: enable_lchown
            value: "true"
          - name: insecure
            value: "false"
# For Swarm, use tcp://of-buildkit:1234
          - name: buildkit_url  
            value: "tcp://127.0.0.1:1234"
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: registry-secret
          readOnly: true
          mountPath: "/home/app/.docker/"
      - name: of-buildkit
        args: ["--addr", "tcp://0.0.0.0:1234"]
#        image: alexellis2/buildkit:2018-04-17
        image: alexellis/buildkit:cda0a64eca0b5404a2a0233ba863606da8d4b7be
        imagePullPolicy: Always
        ports:
        - containerPort: 1234
          protocol: TCP
        securityContext:
          privileged: true

