apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: of-router
  namespace: openfaas
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io.scrape: "false"
      labels:
        app: of-router
    spec:
      containers:
      - name: of-router
        image: openfaas/cloud-router:0.5.0
        imagePullPolicy: Always
        env:
          - name: upstream_url
            value: "http://gateway.openfaas:8080"
          - name: port
            value: "8080"
          - name: timeout
            value: "60s"
          - name: auth_url
            value: "http://auth.openfaas:8080"
        ports:
        - containerPort: 8080
          protocol: TCP

